'''
SYSTEM CONSTANTS:
    - RESOLUTION
    - MIDLE POINT
    - FPS
    - DELTA TIME

'''
(X_RES, Y_RES) = (700, 900)
(X_MID, Y_MID) = (X_RES / 2, Y_RES / 2)
FPS = 30
DELTA = 1/60

'''
COLORS:
    - BACKGROUND COLOR
'''
BG = (20,20,20)

'''
PARTICLES CONSTATS:
    - SPACING BETWEEN PARTICLES
    - MASS OF EACH PARTICLE
    - SMOOTHING RADIUS FOR CALCULATING DENSITY
    - RADIUS OF EACH PARTICLE
'''
SPC = 15
MASS = 1
S_RAD = 100
RAD = 5

'''
PHYSICS CONSTANTS:
    - GRAVITATIONAL ACCELERATION
    - TARGET DENSITY OF THE FLUID
    - PRESSURE MULTIPLIER FOR CALCULATINF PRESSURE FORCE
'''
G = 9.81
TARGET_DENSITY = 0.0001
PRESSURE_MULTIPLIER = 10 * 100000
