#SETTINGS
'''
GRAVITY = 0 => NO GRAVITY
GRAVITY = 1 => WITH GRAVITY
'''
GRAVITY = 1

'''
SETUP_SETTING = 0 => GRID BASED SETUP FOR THE PARTCLES
SETUP_SETTING = 1 => RANDOM POSITION SETUP FOR PARTICLES
'''
SETUP_SETTING = 1

'''
SQUARE ROOT OF THE NUMBER OF PARTICLES
'''
NUM = 15
